---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stalwart-proxy-config
  labels:
    app.kubernetes.io/name: stalwart-proxy
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  # Provide an appropriate config file for your environment using Kustomize.
  #
  # The format of this config file is explained here:
  #    https://stalw.art/docs/migration/proxy/configuration/
  # Example configs for our use case can be found here:
  #    https://stalw.art/docs/migration/proxy/examples/stalwart-upgrade/
  config.toml: |
    # TODO
