---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stalwart-config
  labels:
    app.kubernetes.io/name: stalwart
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  config.json: |
    {"@type": RocksDB, "path": "/var/lib/stalwart"}
