---
# Import secrets for use with Stalwart
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stalwart-recovery-admin
  namespace: thundermail
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: stalwart-credentials
    creationPolicy: Owner
  data:
    - secretKey: STALWART_RECOVERY_ADMIN
      remoteRef:
        key: mzla/dev/stalwart-recovery-admin
        property: recovery_admin
