# Apply the nginx pod security group to the nginx pods
---
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: stalwart-nginx
  namespace: thundermail
spec:
  securityGroups:
    groupIds:
      - "sg-05dbad621d7b95ab4" # stalwart-nginx-authdev
