# A Redis cluster for the proxy to store its mappings in. This must be redundant because the
# mappings cannot be determined from system state if the backend data is lost.
---
apiVersion: elasticache.services.k8s.aws/v1alpha1
kind: ReplicationGroup
metadata:
  name: stalwart-migration-proxy-redis
  namespace: thundermail
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicationGroupID: stalwart-migration-proxy-redis
  description: "Stalwart Proxy Redis - Account migration mappings"
  engine: redis
  engineVersion: "7.1"
  cacheNodeType: cache.t3.micro
  numNodeGroups: 1
  replicasPerNodeGroup: 1
  cacheSubnetGroupName: stalwart-redis-migration-proxy-subnet-group
  securityGroupRefs:
    - from:
        name: stalwart-migration-proxy-elasticache-redis
        namespace: thundermail
  transitEncryptionEnabled: true
  atRestEncryptionEnabled: true
  automaticFailoverEnabled: false
  tags:
    - key: application
      value: thundermail
    - key: managed-by
      value: ack
