---
# The stalwart-migration-proxy-redis-write service maps to the Serverless Redis cache's master endpoint
apiVersion: v1
kind: Service
metadata:
  name: stalwart-migration-proxy-redis
spec:
  externalName: ""
