---
# ConfigMap containing the nginx configuration file
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: thundermail
data:
  nginx.conf: |
    # Nginx does support special mail proxy services --
    #     https://docs.nginx.com/nginx/admin-guide/mail-proxy/mail-proxy/
    # -- but they are built around the needs of legacy mail systems. Stalwart handles these things
    # for us internally now, and we should allow it to do so. Therefore, we use a standard TCP
    # reverse proxy configuration for our purposes.
    #    https://docs.nginx.com/nginx/admin-guide/load-balancer/tcp-udp-load-balancer/

    stream {
      # The upstream name "stalwart-mail" is for reference in the "server" blocks below.
      upstream stalwart-mail {
        # The server name "stalwart-mail" below refers to the Kubernetes Service of that name. We
        # pass this traffic directly through for Stalwart to deal with.
        server stalwart-mail;
      }

      server {
        listen 465;
        proxy_connect_timeout 1s;
        proxy_timeout 3s;
        proxy_pass stalwart-mail:465;
      }

      server {
        listen 993;
        proxy_connect_timeout 1s;
        proxy_timeout 3s;
        proxy_pass stalwart-mail:993;
      }

      server {
        listen 4190;
        proxy_connect_timeout 1s;
        proxy_timeout 3s;
        
        proxy_pass stalwart-mail:4190;
      }
    }

    # HTTP traffic to Stalwart is always encrypted. We need to decrypt it here so we can determine
    # if the traffic, based on the HTTP path, is permissible. While most of Stalwart's API functions
    # are acceptable or required for users to access, we wish to deny access to any administrative
    # functions, even user account self-service functions (since these are handled instead by our
    # own thunderbird-accounts project). All other HTTP-based traffic is sent on to the real
    # Stalwart host upstream.
    #
    # Documentation for HTTP server configuration can be found here:
    # https://nginx.org/en/docs/http/configuring_https_servers.html

    http {
      # --- SSL Configuration ---
      # These files are populated as volumes mounted to the pods from secrets drawn from an
      # external secret store.
      ssl_certificate /etc/nginx/domain.crt;
      ssl_certificate_key /etc/nginx/domain.key;
      ssl_session_cache shared:SSL:10m;
      ssl_session_timeout 10m;

      upstream stalwart-https {
        # The "stalwart-https" server is a Kubernetes Service exposing Stalwart's HTTPS port to
        # internal sources.
        server stalwart-https;
      }
      server {
        server_name mail.dev-thundermail.com;
        listen 443 ssl;
        keepalive_timeout 60s;
        proxy_connect_timeout 1s;
        proxy_timeout 3s;

        # Specifically block access to these routes
        location ^~ /account {  # Stalwart's user account settings system, superceded by thunderbird-accounts
          return 404;
        }

        location ^~ /admin {  # Stalwart's web admin console, only accessible by private route
          return 404;
        }

        location ^~ /api {  # Stalwart's underlying API system, only accessible by private route
          return 404;
        }

        # All other routes are acceptable, and should be proxied to the backend
        location ^~ / {
          proxy_pass stalwart-https:443;
        }
      }
    }

    # Small HTTP server to serve health checks for the nginx service itself.
    http {
      listen 80;
      # Return 200s for calls to exactly `/` (no subpaths)
      location = / {
        return 200;
      }
      # Return 404s for anything else
      location / {
        return 404;
      }
    }
