---
# SSL certificate and private key for *.dev-thundermail.com
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ssl-certificate
  namespace: thundermail
spec:
  data:
    - secretKey: CERTIFICATE_CHAIN
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: "mzla/tb-dev/dev-thundermail.com-ssl"
        property: certificate-chain
    - secretKey: PRIVATE_KEY
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: "mzla/tb-dev/dev-thundermail.com-ssl"
        property: private-key
