# Apply the nginx pod security group to the nginx pods
---
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: stalwart-nginx
  namespace: thundermail
spec:
  securityGroups:
    groupIds:
      - "sg-0b48ac1bbc0bc729f" # stalwart-nginx-thundermail
