---
# The stalwart-mail service creates a ClusterIP Service which allows access from other internal
# services. This allows us to intercept traffic with nginx and apply special routing rules. This
# service acts as the origin for proxied traffic.
apiVersion: v1
kind: Service
metadata:
  name: stalwart-mail
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: ClusterIP
  selector:
    app: stalwart
  ports:
    - name: https
      port: 443
      targetPort: https
    - name: smtps
      port: 465
      targetPort: smtps
    - name: starttls
      port: 587
      targetPort: starttls
    - name: imaps
      port: 993
      targetPort: imaps
    - name: sieve
      port: 4190
      targetPort: sieve

---
# The stalwart-https service creates a ClusterIP Service which allows access from other internal
# services. We could instead use the stalwart-admin Service below, but then we would be routing
# traffic from nginx on a node out to a load balancer and back into the cluster. This allows a more
# direct path instead, from a trusted source.
apiVersion: v1
kind: Service
metadata:
  name: stalwart-https
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: ClusterIP
  selector:
    app: stalwart
  ports:
    - name: https
      port: 443
      targetPort: https

---
# We have to expose the management interface so that Accounts can access it, but a ClusterIP is
# insufficient because that IP isn't resolvable from outside the cluster. Instead, we use a
# LoadBalancer type, but annotate it for non-exposure, except to the appropriate sources. Tailscale
# will still have the service in the mesh net for rescue access.
apiVersion: v1
kind: Service
metadata:
  name: stalwart-admin
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    # EKS-specific annotations are documented in "Use Service Annotations to configure Network Load Balancers":
    # https://docs.aws.amazon.com/eks/latest/userguide/auto-configure-nlb.html
    # A full list of annotations supported by the AWS Load Balancer controller can be found here:
    # https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/service/annotations/
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-attributes: "load_balancing.cross_zone.enabled=true"
    service.beta.kubernetes.io/aws-load-balancer-name: "stalwart-admin"
    
    # Update the below values in overlays
    service.beta.kubernetes.io/aws-load-balancer-subnets: ""
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "environment=not_set,project=not_set"
    service.beta.kubernetes.io/aws-load-balancer-security-groups: ""
spec:
  type: LoadBalancer
  selector:
    app: stalwart
  ports:
    - name: https
      port: 443
      targetPort: https

---
# The stalwart-mgmt service creates a ClusterIP Service which is used by Tailscale for private
# management access. This service/port is not exposed outside of the cluster. Technically, other
# services on the cluster can access this as well, though we should avoid that.
apiVersion: v1
kind: Service
metadata:
  name: stalwart-mgmt
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: ClusterIP
  selector:
    app: stalwart
  ports:
    - name: mgmt
      port: 8080
      targetPort: mgmt
