---
# Set the appropriate subnet IDs for tb-dev's private network subnets
apiVersion: elasticache.services.k8s.aws/v1alpha1
kind: CacheSubnetGroup
metadata:
  name: stalwart-redis-subnet-group
  namespace: thundermail
spec:
  cacheSubnetGroupName: "thundermail-authdev-stalwart-redis"

  cacheSubnetGroupDescription: "Stalwart Redis subnet group for thundermail-authdev" 

  subnetIDs:
    - "subnet-044e18f3022fb9ee1"  # mzla-tb-dev-private-eu-central-1a
    - "subnet-01084662e5e16dce9"  # mzla-tb-dev-private-eu-central-1b
