---
# Set the appropriate subnet IDs for tb-dev's private network subnets
apiVersion: elasticache.services.k8s.aws/v1alpha1
kind: CacheSubnetGroup
metadata:
  name: stalwart-redis-subnet-group
  namespace: thundermail
spec:
  # SETUP: Specify a unique name for your cache
  cacheSubnetGroupName: "" 

  # SETUP: Specify your deployment in the description
  cacheSubnetGroupDescription: "Stalwart Redis subnet group for <deployment>" 

  subnetIDs:
    # SETUP: Uncomment the set of subnet IDs below that matches your deployment environment

    # tb-dev:
    # - "subnet-044e18f3022fb9ee1"  # mzla-tb-dev-private-eu-central-1a
    # - "subnet-01084662e5e16dce9"  # mzla-tb-dev-private-eu-central-1b

    # tb-prod:
    # - "subnet-085a71891b27bd24c" # mzla-tb-prod-private-eu-central-1a
    # - "subnet-0b863a1876ec121cb" # mzla-tb-prod-private-eu-central-1b
