---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stalwart-recovery-admin
  namespace: thundermail
spec:
  data:
    - secretKey: STALWART_RECOVERY_ADMIN
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        # SETUP: Set the name of the AWS secret to pull this secret value from
        key: ""
        property: recovery_admin

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stalwart-postgresql-admin-password
  namespace: thundermail
spec:
  data:
    - secretKey: STALWART_POSTGRESQL_ADMIN_PASSWORD
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        # SETUP: Set the name of the AWS secret to pull this secret value from
        key: ""
        property: password

# SETUP: If you want Stalwart to manage a DNS domain residing in Cloudflare, you will need to
#        provide credentials through this ExternalSecret. Uncomment this and update the "key" field
#        with the name of the AWS secret containing the token.
# ---
# # Cloudflare API token for automatic DNS management
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: stalwart-cloudflare-api-token
#   namespace: thundermail
#   annotations:
#     argocd.argoproj.io/sync-wave: "1"
# spec:
#   data:
#     - secretKey: STALWART_CLOUDFLARE_API_TOKEN
#       remoteRef:
#         conversionStrategy: Default	
#         decodingStrategy: None
#         metadataPolicy: None
#         # SETUP: Set the name of the AWS secret to pull this secret value from
#         key: ""
#         # SETUP: If your AWS secret uses a different key to store the token, update this line:
#         property: "api_token"

# SETUP: If you do not intend on using Cloudflare DNS auto-management, uncomment this patch instead,
#        preventing an API token secret from being created.
# ---
# $patch: delete
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: stalwart-cloudflare-api-token
#   namespace: thundermail
