---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stalwart-recovery-admin
  namespace: thundermail
spec:
  data:
    - secretKey: STALWART_RECOVERY_ADMIN
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        # SETUP: Set the name of the AWS secret to pull this secret value from
        key: ""
        property: recovery_admin

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stalwart-postgresql-admin-password
  namespace: thundermail
spec:
  data:
    - secretKey: STALWART_POSTGRESQL_ADMIN_PASSWORD
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        # SETUP: Set the name of the AWS secret to pull this secret value from
        key: ""
        property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-secrets
  namespace: thundermail
spec:
  data:
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        # SETUP: Set the name of the AWS secret to pull this secret value from
        key: ""
        property: apiToken
    - secretKey: CLOUDFLARE_ACCOUNT_ID
      remoteRef:
        # SETUP: Set the name of the AWS secret to pull this secret value from
        key: ""
        property: accountID
