---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stalwart
  namespace: thundermail
  labels:
    app.kubernetes.io/name: stalwart
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    eks.amazonaws.com/role-arn: "" # Populate with Kustomize
