---
# The stalwart-mail service creates a public load balancer exposing mail services to the world.
apiVersion: v1
kind: Service
metadata:
  name: stalwart-mail
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    # EKS-specific annotations are documented in "Use Service Annotations to configure Network Load Balancers":
    # https://docs.aws.amazon.com/eks/latest/userguide/auto-configure-nlb.html
    # A full list of annotations supported by the AWS Load Balancer controller can be found here:
    # https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/service/annotations/
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-attributes: "load_balancing.cross_zone.enabled=true"
    
    # Update the below values in overlays
    service.beta.kubernetes.io/aws-load-balancer-subnets: ""
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "environment=not_set,project=not_set"
spec:
  type: LoadBalancer
  selector:
    app: stalwart
  loadBalancerSourceRanges: 
    - 0.0.0.0/0
  ports:
    - name: smtps
      port: 465
      targetPort: smtps
    - name: imaps
      port: 993
      targetPort: imaps
    - name: sieve
      port: 4190
      targetPort: sieve
    - name: https
      port: 443
      targetPort: https

---
# The stalwart-admin service creates a ClusterIP service to keep this private. The Tailscale ingress
# set up in the platform-infrastructure repo will expose this through the private meshnet.
apiVersion: v1
kind: Service
metadata:
  name: stalwart-admin
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: ClusterIP
  selector:
    app: stalwart
  ports:
    - name: mgmt
      port: 8080
      targetPort: mgmt
