---
# Cloudflare Tunnel for dev-thundermail.com: our various mail services
apiVersion: networking.cfargotunnel.com/v1alpha2
kind: Tunnel
metadata:
  name: stalwart-tunnel
  namespace: thundermail
  annotations:
    # Stage 4 is late enough that the deployment and service are created but still before the tunnel binding
    argocd.argoproj.io/sync-wave: "4"  
spec:
  newTunnel:
    name: stalwart-mzla-eks-tb-dev01
  cloudflare:
    domain: dev-thundermail.com
    secret: cloudflare-secrets
    accountId: "407a3cd7b36b3ec71bf765856c90ae8c"

# ---
# # Bind the above tunnel to the Stalwart service
# apiVersion: networking.cfargotunnel.com/v1alpha1
# kind: TunnelBinding
# metadata:
#   name: tb-dev-stalwart-admin-binding
#   namespace: thundermail
#   annotations:
#     # Make sure the tunnel exists before trying to bind it
#     argocd.argoproj.io/sync-wave: "5"
# subjects:
#   - kind: Service
#     name: stalwart
#     spec:
#       fqdn: mail.dev-thundermail.com
#       protocol: http
#       target: http://stalwart.thundermail.svc:8080
# tunnelRef:
#   kind: Tunnel
#   name: stalwart-tunnel
# 