---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stalwart-config
  labels:
    app.kubernetes.io/name: stalwart
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  # The format of this config file is a JSON representation of a Stalwart DataStore object.
  # Ref: https://stalw.art/docs/ref/object/data-store/
  config.json: '{"@type": "PostgreSql", "host": "stalwart-postgresql.cf6we8ukyqsy.eu-central-1.rds.amazonaws.com", "authSecret": { "EnvironmentVariable": { "variableName": "STALWART_POSTGRESQL_ADMIN_PASSWORD"}}}'
