---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stalwart
  namespace: thundermail
  labels:
    app.kubernetes.io/name: stalwart
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    eks.amazonaws.com/role-arn: "arn:aws:iam::718959508124:role/mzla-tb-dev-stalwart-server"