---
# The nginx service creates a public load balancer exposing our nginx proxy to the world.
apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    # EKS-specific annotations are documented in "Use Service Annotations to configure Network Load Balancers":
    # https://docs.aws.amazon.com/eks/latest/userguide/auto-configure-nlb.html
    # A full list of annotations supported by the AWS Load Balancer controller can be found here:
    # https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/service/annotations/
    service.beta.kubernetes.io/aws-load-balancer-name: stalwart-nginx-public
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-attributes: "load_balancing.cross_zone.enabled=true"
    
    # Update the below values in overlays
    service.beta.kubernetes.io/aws-load-balancer-subnets: ""
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "environment=not_set,project=not_set"
spec:
  type: LoadBalancer
  selector:
    # The public load balancer should always route traffic to our internal proxy, which will route
    # that traffic internally according to our rules.
    app: stalwart-nginx
  loadBalancerSourceRanges: 
    - 0.0.0.0/0
  ports:
    - name: https
      port: 443
      targetPort: https
    - name: smtps
      port: 465
      targetPort: smtps
    - name: imaps
      port: 993
      targetPort: imaps
    - name: sieve
      port: 4190
      targetPort: sieve
