# Apply the stalwart pod security group to the Stalwart server pods
---
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: stalwart-server
  namespace: thundermail
spec:
  securityGroups:
    groupIds:
      - "sg-0125a177e851755df" # stalwart-server-thundermail
