---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stalwart
  namespace: thundermail
  annotations:
    # SETUP: Insert the ARN of the IAM Role that the Stalwart pods will assume
    eks.amazonaws.com/role-arn: "arn:aws:iam::689951664252:role/tb-dev-tm-thundermail-stalwart"
