---
# Import secrets for use with Stalwart's PostgreSQL backend from AWS Secrets Manager
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-credentials
  namespace: thundermail
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: postgresql-credentials
    creationPolicy: Owner
  data:
    - secretKey: POSTGRESQL_DB
      remoteRef:
        key: mzla/tb-dev/postgresql-connection
        property: db
    - secretKey: POSTGRESQL_PASSWORD
      remoteRef:
        key: mzla/tb-dev/postgresql-connection
        property: password
    - secretKey: POSTGRESQL_USER
      remoteRef:
        key: mzla/tb-dev/postgresql-connection
        property: user
