---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: stalwart-migration-proxy
  namespace: thundermail
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stalwart-migration-proxy
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
