---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases

namespace: thundermail

images:
  - name: stalwartlabs/stalwart
    newTag: v0.16.5

patches:
  - path: stalwart/aws/elasticache.yaml
  - path: stalwart/aws/s3.yaml
  - path: stalwart/aws/security-groups.yaml
  - path: stalwart/aws/subnet-groups.yaml
  - path: stalwart/configmap.yaml
  - path: stalwart/secrets.yaml
  - path: stalwart/service.yaml
  - path: stalwart/serviceaccount.yaml

  - target:
      kind: Deployment
      name: stalwart
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STALWART_PUBLIC_URL
          value: "https://mail.dev-thundermail.com"
