---
namespace: thundermail

resources:
  - bases/cloudflare-tunnel.yaml
  - bases/configmap.yaml
  - bases/deployment.yaml
  - bases/secrets.yaml
  - bases/service.yaml
  - bases/serviceaccount.yaml

commonLabels:
  app: stalwart