---
apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: stalwart-s3-bucket
  namespace: thundermail
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  name: mzla-eks-tb-dev-stalwart-blob-storage
  encryption:
    applyServerSideEncryptionByDefault:
      sseAlgorithm: AES256
  namespace: account-regional
  versioning:
    status: Enabled