---
apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: stalwart-s3-bucket
  namespace: thundermail
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  name: mzla-eks-tb-dev-stalwart-blob-storage-718959508124-eu-central-1-an
  encryption:
    rules:
      - applyServerSideEncryptionByDefault:
          sseAlgorithm: AES256
  namespace: account-regional
  versioning:
    status: Enabled