# Build security groups for each app
---
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: stalwart-server
  namespace: thundermail
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  description: SG for Stalwart server containers running in Kubernetes
  egressRules:
    - fromPort: 0
      toPort: 0
      ipProtocol: "-1"
      ipRanges:
        - cidrIp: "0.0.0.0/0"
          description: "Allow all egress"
  ingressRules: []

# Build SecurityGroupPolicies matching each pod deployment with each app SG
# (https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/master/config/crd/bases/vpcresources.k8s.aws_securitygrouppolicies.yaml)
---
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: stalwart-server
  namespace: thundermail
spec:
  podSelector:
    matchLabels:
      app: stalwart
  securityGroups:
    groupIds:
      - sg-07624df6ceb8865ec  # EKS cluster security group
      # - Add ID for stalwart-server app SG

# Build security groups for each backend service (RDS, Redis) allowing access from the app SGs
---
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: stalwart-rds-postgresql
  namespace: thundermail
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  description: SG for Stalwart's backend PostgreSQL instance on RDS
  egressRules:
    - fromPort: 0
      toPort: 0
      ipProtocol: "-1"
      ipRanges:
        - cidrIp: "0.0.0.0/0"
          description: "Allow all egress"
  ingressRules: []
  # ingressRules:
  #   - fromPort: 5432
  #     toPort: 5432
  #     ipProtocol: tcp
  #     userIDGroupPairs:
  #       - description: Allow traffic from Stalwart's server containers
  #         groupId: Add ID for stalwart-server app SG
