---
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: stalwart-elasticache-redis
  namespace: thundermail
spec:
  vpcID: vpc-0e0f4b8d603d463e0
  ingressRules:
    - fromPort: 6379
      toPort: 6379
      ipProtocol: tcp
      userIDGroupPairs:
        - description: Allow traffic from Stalwarts server containers
          groupID: sg-0225f0469688b6324  # Stalwart pods

---
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: stalwart-server
  namespace: thundermail
spec:
  securityGroups:
    groupIds:
      - sg-07624df6ceb8865ec  # EKS cluster
      - sg-0225f0469688b6324  # Stalwart pods

---
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: stalwart-server
  namespace: thundermail
spec:
  vpcID: vpc-0e0f4b8d603d463e0
  ingressRules:
    - fromPort: 8080
      toPort: 8080
      ipProtocol: tcp
      userIDGroupPairs:
        - description: Kubelet probes from EKS cluster SG
          groupID: sg-08c51d43c4a250a81 # eks-cluster-sg-mzla-eks-tb-dev01

