---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
  namespace: thundermail
spec:
  # SETUP: Adjust the scaling options below to suit your Stalwart deployment
  minReplicas: 1
  maxReplicas: 1
