---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stalwart-recovery-admin
  namespace: thundermail
spec:
  data:
    - secretKey: STALWART_RECOVERY_ADMIN
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: "mzla/tb-dev/thundermail-tbirdemail/stalwart-recovery-admin"
        property: recovery_admin

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stalwart-postgresql-admin-password
  namespace: thundermail
spec:
  data:
    - secretKey: STALWART_POSTGRESQL_ADMIN_PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: "mzla/tb-dev/thundermail-tbirdemail/stalwart-postgresql-admin-credential"
        property: password
