# Apply the stalwart pod security group to the Stalwart server pods
---
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: stalwart-server
  namespace: thundermail
spec:
  securityGroups:
    groupIds:
      - "sg-080a5f76daa4c90ab" # stalwart-server-tbirdemail"
