---
# Security group for the stalwart-proxy pods
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: stalwart-proxy
  namespace: thundermail
spec:
  vpcID: vpc-0e0f4b8d603d463e0
  egressRules:
    - fromPort: 0
      toPort: 0
      ipProtocol: "-1"
      ipRanges:
        - cidrIP: "0.0.0.0/0"
          description: "Allow all egress"
  ingressRules:
    # stalwart-mail has certain private allowances for using port 8080, the management service. This
    # service is never exposed to public users, and so there is no proxy mechanism for it. The rest
    # of these are service ports which are exposed through the nginx proxy. We set the migration
    # proxy up to support those.
    - fromPort: 443
      toPort: 443
      ipProtocol: tcp
      userIDGroupPairs:
        - description: Allow HTTPS service traffic from the proxy load balancer
          groupID: "" # stalwart-proxy-lb
    - fromPort: 465
      toPort: 465
      ipProtocol: tcp
      userIDGroupPairs:
        - description: Allow SMTPS service traffic from the proxy load balancer
          groupID: ""  # stalwart-proxy-lb
    - fromPort: 993
      toPort: 993
      ipProtocol: tcp
      userIDGroupPairs:
        - description: Allow IMAPS service traffic from the proxy load balancer
          groupID: ""  # stalwart-proxy-lb
    - fromPort: 4190
      toPort: 4190
      ipProtocol: tcp
      userIDGroupPairs:
        - description: Allow ManageSieve service traffic from the proxy load balancer
          groupID: ""  # stalwart-proxy-lb

---
# Security group for the stalwart-proxy service's load balancer
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: stalwart-proxy-lb
  namespace: thundermail
spec:
  vpcID: vpc-0e0f4b8d603d463e0

# --- Build SecurityGroupPolicies matching each pod deployment with each app SG ---
# (https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/master/config/crd/bases/vpcresources.k8s.aws_securitygrouppolicies.yaml)
---
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: stalwart-proxy
  namespace: thundermail
spec:
  podSelector:
    matchLabels:
      app: stalwart-proxy
  securityGroups:
    groupIds: [] # Populate with Kustomize


