---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stalwart
  namespace: thundermail
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::689951664252:role/mzla-tb-prod-stalwart-server"
