---
apiVersion: networking.cfargotunnel.com/v1alpha2
kind: Tunnel
metadata:
  name: stalwart-tunnel
  namespace: thundermail
spec:
  newTunnel:
    name: stalwart-mzla-eks-tb-dev01
  cloudflare:
    accountId: "407a3cd7b36b3ec71bf765856c90ae8c"
    domain: dev-thundermail.com

---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: stalwart-tunnel-binding
  namespace: thundermail
subjects:
  - kind: Service
    name: stalwart
    spec:
      fqdn: mail.dev-thundermail.com
      protocol: http
      target: http://stalwart.thundermail.svc:8080
tunnelRef:
  kind: Tunnel
  name: stalwart-tunnel
