---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stalwart-recovery-admin
  namespace: thundermail
spec:
  data:
    - secretKey: STALWART_RECOVERY_ADMIN
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: mzla/tb-dev/stalwart-recovery-admin
        property: recovery_admin

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stalwart-postgresql-admin-password
  namespace: thundermail
spec:
  data:
    - remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: mzla/tb-dev/stalwart-postgresql-admin-credential
        property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-secrets
  namespace: thundermail
spec:
  data:
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: mzla/tb-dev/cloudflare
        property: apiToken
    - secretKey: CLOUDFLARE_ACCOUNT_ID
      remoteRef:
        key: mzla/tb-dev/cloudflare
        property: accountID
