---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stalwart
  namespace: thundermail
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::718959508124:role/mzla-tb-dev-stalwart-server"
