---
apiVersion: v1
kind: Service
metadata:
  name: stalwart-mail
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-subnets: "mzla-tb-dev-public-eu-central-1a,mzla-tb-dev-public-eu-central-1b"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "environment=prod,project=mzla-tb-dev"