---
# Bearer token for accessing Stalwart Proxy's API
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stalwart-migration-proxy-bearer-token
  namespace: thundermail
spec:
  data:
    - secretKey: STALWART_MIGRATION_PROXY_BEARER_TOKEN
      remoteRef:
        key: "mzla/tb-dev/stalwart-migration-proxy-bearer-token"
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        property: recovery_admin




