---
# The stalwart-migration-proxy-redis-write service maps to the Serverless Redis cache's master endpoint
apiVersion: v1
kind: Service
metadata:
  name: stalwart-migration-proxy-redis
spec:
  externalName: "master.stalwart-migration-proxy-redis.psueny.euc1.cache.amazonaws.com"
