---
namespace: thundermail

resources:
  - bases/elasticache-subnet-group.yaml
  - bases/elasticache.yaml
  - bases/rds-subnet-group.yaml
  - bases/rds.yaml
  - bases/s3.yaml
  - bases/security-groups.yaml

commonLabels:
  app: stalwart
